name: Build GordiPos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restaurar paquetes NuGet
      # Aquí le decimos que busque cualquier archivo de proyecto
      run: nuget restore **/*.slnx

    - name: Compilar Proyecto
      # Usamos el asterisco para que encuentre el proyecto sin importar la carpeta
      run: msbuild **/*.slnx /p:Configuration=Release /p:DeployOnBuild=true
