name: Build GordiPos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restaurar paquetes NuGet
      # Usamos el nombre exacto que vimos en tu pestaña Code
      run: nuget restore "interfaz de caja registradora.slnx"

    - name: Compilar Proyecto
      # Usamos el nombre exacto aquí también
      run: msbuild "interfaz de caja registradora.slnx" /p:Configuration=Release
